In [4]:
import numpy as np
from sklearn.cluster import AffinityPropagation
import distance
from sklearn import metrics as mt

words = words = [
    "conseguiu",
    "conseigiu",
    "conseguiu",
    "conseguiu",
    "concegiu",
    "conceguiu",
    "consegui",
    "consegi",
    "ninguém",
    "ninguem",
    "nigem",
    "niguem",
    "ningem",
    "assalto",
    "assauto",
    "asauto",
    "asalto",
    "assautu",
    "asautu",
    "alguém",
    "alguem",
    "alquem",
    "agluém",
    "algem",
    "algém",
    "auguem",
    "auguém",
    "exame",
    "ezame",
    "exeme",
    "embaixo",
    "embaio",
    "embaixo",
    "embaixu",
    "enbaixu",
    "embaixio",
    "enbaixo",
    "enbeixo",
    "fez",
    "fes",
    "também",
    "tamém",
    "tanbem",
    "faz",
    "fas",
    "fás",
    "guerra",
    "guera",
    "guarra",
    "exemplo",
    "ezemplo",
    "exenplo",
    "caiu",
    "ciau",
    "cai",
    "enxergar",
    "enchergar",
    "enxerg",
    "almoço",
    "aumoco",
    "aumoço",
    "almoco",
    "vez",
    "ves",
    "fez",
    "relógio",
    "reógio",
    "relogio",
    "relógiu",
    "relogiu",
    "jeito",
    "geito",
    "jeitto",
    "disse",
    "dise",
    "árvore",
    "ávore",
    "arvore",
    "arvre",
    "arvure",
    "árvure",
    "arvere",
    "árvere",
    "borracha",
    "borraca",
    "boracha",
    "borraca",
    "pegue",
    "pegue",
    "peg",
    "saudade",
    "saudede",
    "saudade",
    "assim",
    "asim",
    "assím",
    "amanhã",
    "amanhã",
    "amanha",
    "correr",
    "corer",
    "correr",
    "brincar",
    "brinca",
    "bringar",
    "homem",
    "omem",
    "home",
    "gente",
    "jenti",
    "genti",
    "viajar",
    "viaja",
    "viajer",
    "certo",
    "sero",
    "certo",
    "encontrou",
    "encontrou",
    "encontou",
    "quente",
    "quenti",
    "quente",
    "cabeça",
    "cabessa",
    "cabecca",
    "professora",
    "professo",
    "professoura",
    "futebol",
    "futebom",
    "futibol",
    "feliz",
    "felez",
    "felis",
    "ajuda",
    "ajuda",
    "aujda",
    "fazer",
    "faser",
    "facer",
    "tenho",
    "tenho",
    "teho",
    "tempo",
    "tempa",
    "tem",
    "tesoura",
    "tisoura",
    "tesora",
    "tisora",
    "muito",
    "muitu",
    "muto",
    "mutio",
    "quando",
    "cuendo",
    "quado",
    "cachorro",
    "gaxorro",
    "caxorro",
    "então",
    "entao",
    "emtão",
    "presente",
    "peresente",
    "prezente",
    "bruxa",
    "brucha",
    "animal",
    "animau",
    "aninal",
    "anemal",
    "girafa",
    "jirafa",
    "grafa",
    "carro",
    "caro",
    "car",
    "porque",
    "porquê",
    "porke",
    "galinha",
    "galin",
    "galinga",
    "menino",
    "meni",
    "men",
    "casa",
    "cassa",
    "ca",
    "escola",
    "escol",
    "esola",
    "ecol",
]

words = np.asarray(words) 
lev_similarity = -1 * np.array(
    [[distance.levenshtein(w1, w2) for w1 in words] for w2 in words],
    dtype = float
)

print(lev_similarity)

affprop = AffinityPropagation(affinity="precomputed", damping=0.5)
affprop.fit(lev_similarity)
print(np.unique(affprop.labels_))
for cluster_id in np.unique(affprop.labels_):
    exemplar = words[affprop.cluster_centers_indices_[cluster_id]]
    cluster = np.unique(words[np.nonzero(affprop.labels_ == cluster_id)])
    cluster_str = ", ".join(cluster)
    print(" - *%s:* %s" % (exemplar, cluster_str))



[[-0. -2. -0. ... -8. -8. -8.]
 [-2. -0. -2. ... -8. -8. -8.]
 [-0. -2. -0. ... -8. -8. -8.]
 ...
 [-8. -8. -8. ... -0. -2. -1.]
 [-8. -8. -8. ... -2. -0. -2.]
 [-8. -8. -8. ... -1. -2. -0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
 - *conseguiu:* concegiu, conceguiu, consegi, consegui, conseguiu, conseigiu
 - *ninguem:* nigem, niguem, ningem, ninguem, ninguém
 - *asauto:* asalto, asauto, asautu, assalto, assauto, assautu
 - *alguém:* agluém, algem, alguem, alguém, algém, alquem, auguem, auguém
 - *exame:* exame, exeme, ezame
 - *embaixo:* embaio, embaixio, embaixo, embaixu, enbaixo, enbaixu, enbeixo
 - *também:* também, tamém, tanbem
 - *guerra:* guarra, guera, guerra
 - *exemplo:* exemplo, exenplo, ezemplo
 - *cai:* ca, cai, caiu, car, caro, casa, ciau, fas
 - *enxergar:* enchergar, enxerg, enxergar
 - *almoco:* almoco, almoço, aumoco, aumoço
 - *fez:* faz, felez, feliz, fes, fez, fás, peg,